import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import spices from "../public/spices.json";
import { useState } from "react";

export default function Home() {
  const [searchTerm, setSearchTerm] = useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.searchBarContainer}>
          <input
            className={styles.searchBar}
            type="text"
            placeholder="Search..."
            onChange={(event) => {
              setSearchTerm(event.target.value);
            }}
          />
        </div>
        <div className={styles.grid}>
          {spices
            .filter((val) => {
              if (searchTerm == "") {
                return val;
              } else if (
                val.name.toLowerCase().includes(searchTerm.toLowerCase())
              ) {
                return val;
              }
            })
            .map((val, key) => {
              return (
                <div className={styles.card} key={key}>
                  <div className={styles.cardName}>
                    <h2>{val.name}</h2>
                  </div>
                  <div className={styles.cardRow}>
                    <h3>Row </h3>
                    <p>{val.row}</p>
                  </div>
                  <div className={styles.cardSide}>
                    <h4>{val.side}</h4>
                  </div>
                  <img className={styles.image} src={val.link} />
                </div>
              );
            })}
        </div>
      </main>
      {/* 
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
